import { Student, AttendanceRecord, HomeworkRecord, AttendanceEvent } from '../types';
import { DEFAULT_SUBJECTS } from './db';

export function generateSampleData(): {
  students: Student[];
  attendance: AttendanceRecord[];
  homework: HomeworkRecord[];
  events: AttendanceEvent[];
} {
  const sampleStudents: Student[] = [
    { id: 'stu-1', name: '张子轩', studentNo: '202401', gradeClass: '初二(3)班', phone: '13800138001', notes: '擅长数学与物理', createdAt: Date.now() - 86400000 * 10 },
    { id: 'stu-2', name: '李雨桐', studentNo: '202402', gradeClass: '初二(3)班', phone: '13800138002', notes: '英语词汇量丰富', createdAt: Date.now() - 86400000 * 9 },
    { id: 'stu-3', name: '王嘉尔', studentNo: '202403', gradeClass: '初二(1)班', phone: '13800138003', notes: '认真踏实', createdAt: Date.now() - 86400000 * 8 },
    { id: 'stu-4', name: '赵梓涵', studentNo: '202404', gradeClass: '初二(2)班', phone: '13800138004', notes: '解题速度快', createdAt: Date.now() - 86400000 * 7 },
    { id: 'stu-5', name: '陈思宇', studentNo: '202405', gradeClass: '初二(1)班', phone: '13800138005', notes: '需加强化学实验理解', createdAt: Date.now() - 86400000 * 6 },
    { id: 'stu-6', name: '林若微', studentNo: '202406', gradeClass: '初二(2)班', phone: '13800138006', notes: '文史素养好', createdAt: Date.now() - 86400000 * 5 },
  ];

  const todayStr = new Date().toISOString().split('T')[0];
  const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];
  const dayBeforeStr = new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0];

  const attendance: AttendanceRecord[] = [
    {
      id: 'att-sample-1',
      studentId: 'stu-1',
      studentName: '张子轩',
      date: todayStr,
      checkInTime: '13:30',
      checkOutTime: '17:45',
      durationMinutes: 255,
      status: 'checked_out',
      note: '准时到场，作业专注',
      createdAt: Date.now() - 14400000,
      updatedAt: Date.now() - 1000000,
    },
    {
      id: 'att-sample-2',
      studentId: 'stu-2',
      studentName: '李雨桐',
      date: todayStr,
      checkInTime: '14:00',
      checkOutTime: undefined,
      durationMinutes: undefined,
      status: 'checked_in',
      note: '正在自习中',
      createdAt: Date.now() - 10800000,
      updatedAt: Date.now() - 10800000,
    },
    {
      id: 'att-sample-3',
      studentId: 'stu-3',
      studentName: '王嘉尔',
      date: todayStr,
      checkInTime: '14:15',
      checkOutTime: '16:30',
      durationMinutes: 135,
      status: 'checked_out',
      createdAt: Date.now() - 9000000,
      updatedAt: Date.now() - 2000000,
    },
    {
      id: 'att-sample-4',
      studentId: 'stu-4',
      studentName: '赵梓涵',
      date: todayStr,
      checkInTime: '14:30',
      status: 'checked_in',
      createdAt: Date.now() - 7200000,
      updatedAt: Date.now() - 7200000,
    },
    // Yesterday
    {
      id: 'att-sample-5',
      studentId: 'stu-1',
      studentName: '张子轩',
      date: yesterdayStr,
      checkInTime: '14:00',
      checkOutTime: '17:30',
      durationMinutes: 210,
      status: 'checked_out',
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now() - 86400000 + 12600000,
    },
    {
      id: 'att-sample-6',
      studentId: 'stu-2',
      studentName: '李雨桐',
      date: yesterdayStr,
      checkInTime: '13:45',
      checkOutTime: '17:00',
      durationMinutes: 195,
      status: 'checked_out',
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now() - 86400000 + 11700000,
    },
    {
      id: 'att-sample-7',
      studentId: 'stu-5',
      studentName: '陈思宇',
      date: dayBeforeStr,
      checkInTime: '14:20',
      checkOutTime: '16:50',
      durationMinutes: 150,
      status: 'checked_out',
      createdAt: Date.now() - 86400000 * 2,
      updatedAt: Date.now() - 86400000 * 2 + 9000000,
    },
  ];

  const events: AttendanceEvent[] = [
    {
      id: 'ev-1',
      studentId: 'stu-1',
      studentName: '张子轩',
      type: 'check_out',
      timestamp: Date.now() - 1000000,
      timeStr: '17:45',
      date: todayStr,
      note: '签退成功，在场时长约 4小时15分钟',
    },
    {
      id: 'ev-2',
      studentId: 'stu-3',
      studentName: '王嘉尔',
      type: 'check_out',
      timestamp: Date.now() - 2000000,
      timeStr: '16:30',
      date: todayStr,
      note: '签退成功，在场时长约 2小时15分钟',
    },
    {
      id: 'ev-3',
      studentId: 'stu-4',
      studentName: '赵梓涵',
      type: 'check_in',
      timestamp: Date.now() - 7200000,
      timeStr: '14:30',
      date: todayStr,
      note: '签到成功',
    },
    {
      id: 'ev-4',
      studentId: 'stu-2',
      studentName: '李雨桐',
      type: 'check_in',
      timestamp: Date.now() - 10800000,
      timeStr: '14:00',
      date: todayStr,
      note: '签到成功',
    },
    {
      id: 'ev-5',
      studentId: 'stu-1',
      studentName: '张子轩',
      type: 'check_in',
      timestamp: Date.now() - 14400000,
      timeStr: '13:30',
      date: todayStr,
      note: '签到成功',
    },
  ];

  const homework: HomeworkRecord[] = [
    {
      id: 'hw-sample-1',
      studentId: 'stu-1',
      studentName: '张子轩',
      subject: '数学',
      taskName: '二次函数图象与性质压轴综合大题5道',
      date: todayStr,
      startTime: '13:45',
      completedAt: '14:45',
      endTime: '14:45',
      durationMinutes: 60,
      status: 'completed',
      scoreOrQuality: 'A',
      notes: '全部答对，逻辑书写规范',
      createdAt: Date.now() - 10000000,
      updatedAt: Date.now() - 10000000,
    },
    {
      id: 'hw-sample-2',
      studentId: 'stu-1',
      studentName: '张子轩',
      subject: '物理',
      taskName: '欧姆定律电功率计算专题训练卷',
      date: todayStr,
      startTime: '15:00',
      completedAt: '16:10',
      endTime: '16:10',
      durationMinutes: 70,
      status: 'completed',
      scoreOrQuality: 'B',
      notes: '滑动变阻器极值分析需留意',
      createdAt: Date.now() - 6000000,
      updatedAt: Date.now() - 6000000,
    },
    {
      id: 'hw-sample-3',
      studentId: 'stu-2',
      studentName: '李雨桐',
      subject: '英语',
      taskName: 'Unit 4 完形填空与阅读理解真题精练',
      date: todayStr,
      startTime: '14:10',
      completedAt: '15:00',
      endTime: '15:00',
      durationMinutes: 50,
      status: 'completed',
      scoreOrQuality: 'A',
      notes: '长难句解析到位，生词已整理笔记',
      createdAt: Date.now() - 8000000,
      updatedAt: Date.now() - 8000000,
    },
    {
      id: 'hw-sample-4',
      studentId: 'stu-2',
      studentName: '李雨桐',
      subject: '语文',
      taskName: '岳阳楼记文言文断句默写与课后习题',
      date: todayStr,
      startTime: '15:15',
      completedAt: '16:00',
      endTime: '16:00',
      durationMinutes: 45,
      status: 'completed',
      scoreOrQuality: 'A',
      notes: '重点虚词掌握熟练',
      createdAt: Date.now() - 4000000,
      updatedAt: Date.now() - 4000000,
    },
    {
      id: 'hw-sample-5',
      studentId: 'stu-3',
      studentName: '王嘉尔',
      subject: '化学',
      taskName: '酸碱中和反应实验探究分析报告',
      date: todayStr,
      startTime: '14:30',
      completedAt: '15:35',
      endTime: '15:35',
      durationMinutes: 65,
      status: 'completed',
      scoreOrQuality: 'B',
      notes: '现象描述准确',
      createdAt: Date.now() - 5000000,
      updatedAt: Date.now() - 5000000,
    },
    {
      id: 'hw-sample-6',
      studentId: 'stu-4',
      studentName: '赵梓涵',
      subject: '数学',
      taskName: '几何全等三角形证明题专项',
      date: todayStr,
      startTime: '14:40',
      completedAt: '15:40',
      endTime: '15:40',
      durationMinutes: 60,
      status: 'completed',
      scoreOrQuality: 'A',
      notes: '辅助线做法巧妙',
      createdAt: Date.now() - 4500000,
      updatedAt: Date.now() - 4500000,
    },
    {
      id: 'hw-sample-7',
      studentId: 'stu-1',
      studentName: '张子轩',
      subject: '化学',
      taskName: '化学式与化合价基础巩固卷',
      date: yesterdayStr,
      startTime: '14:30',
      completedAt: '15:20',
      endTime: '15:20',
      durationMinutes: 50,
      status: 'completed',
      scoreOrQuality: 'A',
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now() - 86400000,
    },
    {
      id: 'hw-sample-8',
      studentId: 'stu-2',
      studentName: '李雨桐',
      subject: '数学',
      taskName: '分式方程应用题训练',
      date: yesterdayStr,
      startTime: '14:15',
      completedAt: '15:30',
      endTime: '15:30',
      durationMinutes: 75,
      status: 'completed',
      scoreOrQuality: 'B',
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now() - 86400000,
    },
    {
      id: 'hw-sample-9',
      studentId: 'stu-5',
      studentName: '陈思宇',
      subject: '历史',
      taskName: '中国近代史时间轴整理与简答题',
      date: dayBeforeStr,
      startTime: '14:30',
      completedAt: '15:25',
      endTime: '15:25',
      durationMinutes: 55,
      status: 'completed',
      scoreOrQuality: 'A',
      createdAt: Date.now() - 86400000 * 2,
      updatedAt: Date.now() - 86400000 * 2,
    },
    {
      id: 'hw-sample-10',
      studentId: 'stu-6',
      studentName: '林若微',
      subject: '地理',
      taskName: '世界气候类型分布特征绘图与总结',
      date: dayBeforeStr,
      startTime: '15:00',
      completedAt: '16:00',
      endTime: '16:00',
      durationMinutes: 60,
      status: 'completed',
      scoreOrQuality: 'A',
      createdAt: Date.now() - 86400000 * 2,
      updatedAt: Date.now() - 86400000 * 2,
    },
  ];

  return {
    students: sampleStudents,
    attendance,
    homework,
    events,
  };
}
